spring.application.name=StudentManagement-redis-1
server.port=8086

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://jchaitra967_db_user:kejrjInKRIzEBPoP@mycluster1.zm7skv4.mongodb.net/StudentManagement?retryWrites=true&w=majority&appName=MyCluster1

spring.data.mongodb.database=StudentManagement

# Upstash Redis
spring.data.redis.host=alert-pony-188211.upstash.io
spring.data.redis.port=6379
spring.data.redis.username=default
spring.data.redis.password=gQAAAAAAAt8zAAIgcDEyMTE2YzAwOTg4MWI0YjJjOTJhZDYzZjc4NzlmMTIxZA
spring.data.redis.ssl.enabled=true

# Enable Redis Cache
spring.cache.type=redis

# Logging
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=TRACE
logging.level.io.lettuce.core=DEBUG